---
title: "fitts_law_analysis"
author: "Grete Liis Reimand"
date: "2026-09-07"
output: html_document
---

```{r setup, include=FALSE}
# load relevant libraries
knitr::opts_chunk$set(echo = TRUE)
library(performance)
library(ggplot2)
library(lmerTest)
library(tidyverse)
```

```{r}
# read in the data
data = read.csv("fitts_law_data.csv")
```

```{r}
# make a model predicting time from difficulty
# include (1|id) for multilevel modelling (fret not, this will be explained in methods3 if you're not familiar with it)

model = lmer(avg_time ~ difficulty_idx + (1|id), data=data)
summary(model)
r2(model)
```

```{r}
# add the model predictions to the data frame
# hint: mutate()

data <- data %>%
  mutate(fit = predict(model))
```


```{r}
# make a ggplot which shows time predictions from difficulty index, with separate lines for each participant

data %>% 
  ggplot(aes(x=difficulty_idx, y=avg_time, color=id)) +
  geom_point()+
  geom_line(aes(y=fit, color=id))+
  labs(title="Fitts' law results", x="Difficulty", y="Time") +
  theme_minimal()
```


